webstore:main AVL LLRBT Reader
		g++ -std=c++11 main.o AVL.o LLRBT.o Reader.o -o webstore

main:
		g++ -std=c++11 -c main.cpp -o main.o

AVL:
		g++ -std=c++11 -c AVL.cpp -o AVL.o

LLRBT:
		g++ -std=c++11 -c LLRBT.cpp -o LLRBT.o

Reader:
		g++ -std=c++11 -c Reader.cpp -o Reader.o